name: elite_auction
description: A new Flutter application.
publish_to: 'none'
version: 1.9.6+21
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  #add packages sorted by name
  animated_search_bar: ^2.3.0
  auto_size_text: ^3.0.0
  badges: ^2.0.3
  carousel_slider: ^4.1.1
  colorful_print: ^0.1.2
  country_code_picker: ^2.0.2
  dio:
  dio_cache_interceptor: ^3.3.1
  dio_cache_interceptor_hive_store: ^3.2.0
  easy_localization: ^3.0.1
  equatable: ^2.0.3
  extended_image: ^6.3.1
  expandable_page_view:
  firebase_auth: ^3.6.4
  firebase_core: ^1.22.0
  firebase_dynamic_links: null
  firebase_messaging: ^13.0.2
  flutter_bloc:
  flutter_google_places: ^0.3.0
  flutter_local_notifications:
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.1.4
  fluttertoast: ^8.0.9
  flutter_update_dialog: ^2.0.0
  font_awesome_flutter:
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  html: ^0.15.0
  internet_connection_checker: ^0.0.1+4
  json_annotation:
  json_serializable: ^6.3.1
  package_info: ^2.0.2
  path: ^1.8.2
  path_provider:
  pdf: ^3.8.4
  printing: ^5.9.3
  pull_to_refresh: ^2.0.0
  pusher_client: 2.0.0
  shared_preferences:
  share_plus: ^4.0.10+1
  shimmer: ^2.0.0
  sizer: ^2.0.15
  syncfusion_flutter_pdfviewer: ^20.3.59
  url_launcher: ^6.1.5
  uuid: ^3.0.7
  video_player: ^2.4.7
  webview_flutter: ^3.0.4
  wechat_assets_picker: ^8.1.4
  wechat_camera_picker: ^3.6.3

dependency_overrides:
  firebase_core_platform_interface: 4.5.1



dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/language/


  fonts:
    - family: Far_two
      fonts:
        - asset: assets/fonts/far-two-light-2op.ttf
    - family: Walter_Becker
      fonts:
        - asset: assets/fonts/WalterBecker-Regular.ttf
    - family: Hani_Arb
      fonts:
        - asset: assets/fonts/HaniArbMedium.ttf
    - family: Farsi_Far_Tow
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_wght.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Medium.ttf
